fix #2, push to svn first
git-svn-id: https://svn.code.sf.net/p/exe-revision/svn/trunk@20 9a7c71a5-0b07-45d0-bdd4-76dc3152a42c

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -39,6 +39,16 @@ do
 			# Update to existing branch, examine new commits
 			range="$remote_sha..$local_sha"
 		fi
+		
+		# check for git-svn commit
+		commit=`git rev-list -n 1 --grep '^git-svn-id: .*@[0-9]\+ .*' --invert-grep "$range"`
+		if [ -n "$commit" ]
+		then
+			echo >&2 "Found INVALID commit in $local_ref, not pushing"
+			echo "Push to SVN first: "
+			echo "git svn rebase && git svn dcommit"
+			exit 1
+		fi 
 
 		# Check for WIP commit
 		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
